import type { NextPage } from 'next'
import Head from 'next/head'
import { useMachine } from '@xstate/react'
import { Zap, ZapOff } from 'react-feather'
import { toggleMachine } from '../machines/toggleMachine'
import { trpc } from '../utils/trpc'

// import { inspect } from '@xstate/inspect'
// if (typeof window !== 'undefined') {
//   inspect({
//     url: 'https://stately.ai/viz?inspect',
//     iframe: false,
//   })
// }

const Home: NextPage = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }])

  // const [state, send] = useMachine(toggleMachine, { devTools: false })

  const utils = trpc.useContext()
  const serverState = trpc.useQuery(['machine.state'])
  const sendToggle = trpc.useMutation(['machine.toggle'], {
    onSuccess() {
      utils.invalidateQueries(['machine.state'])
    },
  })

  // xstate values
  // const value = state.value as string
  // const isOn = state.matches('on')
  // const toggle = () => send('TOGGLE')

  // tRPC values
  const value = serverState.data
  const isOn = serverState.data === 'on'
  const toggle = () => sendToggle.mutate()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <div id="icon" className="relative">
          <div
            className={`absolute -inset-1 rounded-full transition-all duration-300 blur-xl ${
              isOn && 'bg-amber-600'
            }`}
          ></div>
          <div className="relative">
            {isOn ? <Zap size={150} /> : <ZapOff size={150} />}
          </div>
        </div>
        <span id="spacer" className="my-2" />
        <h1 className="text-3xl font-bold">{value}</h1>
        <span id="spacer" className="my-6" />
        <button
          onClick={toggle}
          className="bg-gray-600 hover:bg-gray-500 active:bg-gray-400 rounded-xl px-4 py-2 transition-all duration-300 hover:shadow-2xl"
        >
          Toggle State
        </button>
        <span id="spacer" className="my-8" />
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-200">
          <span className="text-purple-400">T3X</span> App
        </h1>
        <div className="text-2xl text-blue-400 flex justify-center items-center w-full">
          {hello.data ? (
            <>
              <p>{hello.data.greeting}</p>
            </>
          ) : (
            <p>Loading..</p>
          )}
        </div>
      </main>
    </>
  )
}

export default Home
